### ISSUE TITLE
Grant publishing ability to additional maintainers

### ISSUE THREAD

**Issue by jasonrudolph** [tree-sitter/ruby-tree-sitter#11]
At the moment, we have just one owner on rubygems: https://rubygems.org/gems/tree-sitter

<img width="299" alt="Screen Shot 2020-07-07 at 3 52 06 PM" src="https://user-images.githubusercontent.com/2988/86835260-d40de180-c069-11ea-8e35-a7041dd4b110.png">

To up the "truck factor" 😇, it would be good to expand that.

---

👋 @gjtorikian: Could you add @tclem and @maxbrunsfeld as owners on rubygems.org so that they're able to publish new versions of the gem?

https://rubygems.org/profiles/tclem
https://rubygems.org/profiles/maxbrunsfeld

**Comment by gjtorikian** [comment]
"Truck factor" or "we need GitHub staff on this"? :wink:

I've added those owners based on their RubyGems emails, have fun!
