### ISSUE TITLE
Doing code folding

### ISSUE THREAD

**Issue by albfan** [tree-sitter/ruby-tree-sitter#6]
I'm working on code folding feature, and want to use tree-sitter

If #5 is resolved, how can I detect all the `{` `}` pairs in a c file to apply fold to them? I know there's a `start_position` and `end_position` where I can ask for `row` and `column`, just trying to figure out names for that symbols `{` `}`

**Comment by maxbrunsfeld** [comment]
The names are "{" and "}".

**Comment by albfan** [comment]
Nice, I suppose seing other nodes, just want to confirm.
